#!/bin/sh

if [ -z $LUA ]; then
LUA=${1:-lua}
fi

for f in test/*.lua
do
  echo Testing $LUA $f
  LUA_PATH=lua/?.lua LUA_CPATH=lua/?.so $LUA $f
  LUA_PATH=lua/?.lua LUA_CPATH=lua/?.so sh/luatrace.profile
  rm trace-out.txt
  echo
done

